# Generated by Django 5.2.14 on 2026-05-20 08:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('committee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم المركز الطبي المحال إليه')),
                ('address', models.CharField(max_length=500, verbose_name='العنوان بالكامل')),
                ('phone_number', models.CharField(max_length=50, verbose_name='أرقام التواصل للجهات الخارجية')),
            ],
            options={
                'verbose_name': 'مركز تحويل خارجي',
                'verbose_name_plural': 'مراكز التحويل الخارجية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ISS', 'تم الإصدار'), ('ACC', 'مقبول في المركز'), ('CMP', 'تم تقديم الخدمة'), ('CNL', 'ملغي')], default='ISS', max_length=3, verbose_name='حالة خطاب التحويل')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ إصدار الخطاب')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='سبب الإلغاء (إن وجد)')),
                ('committee_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='committee.committeecase', verbose_name='حالة اللجنة الطبية')),
                ('referral_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='referrals.referralcenter', verbose_name='المركز الموجه له الإحالة')),
            ],
            options={
                'verbose_name': 'خطاب تحويل مريض',
                'verbose_name_plural': 'خطابات تحويل المرضى',
                'ordering': ['-issued_at'],
            },
        ),
    ]
