# Generated by Django 5.2.14 on 2026-06-03 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='referrals.referralcenter', verbose_name='المركز الموجه له الحالة'),
        ),
    ]
