# Generated by Django 5.2.14 on 2026-05-20 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255, unique=True, verbose_name='اسم الطبيب')),
            ],
            options={
                'verbose_name': 'طبيب لجنة',
                'verbose_name_plural': 'أطباء اللجان',
                'ordering': ['doctor_name'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150, verbose_name='تصنيف الإجراء الطبي')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم الإجراء')),
                ('requires_referral', models.BooleanField(default=False, verbose_name='يتطلب تحويل لمركز خارجي')),
            ],
            options={
                'verbose_name': 'إجراء طبي',
                'verbose_name_plural': 'الإجراءات الطبية',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PND', 'قيد الانتظار'), ('RVW', 'قيد المراجعة'), ('APP', 'تمت الموافقة'), ('REJ', 'مرفوض'), ('DEF', 'مؤجل لجلسة أخرى')], default='PND', max_length=3, verbose_name='حالة القرار')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='التفاصيل والتشخيص المقابل المعروض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العرض')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='committee_cases', to='patients.patient', verbose_name='المريض')),
                ('committee_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='committee.committeesession', verbose_name='جلسة اللجنة')),
            ],
            options={
                'verbose_name': 'حالة معروضة',
                'verbose_name_plural': 'الحالات المعروضة باللجنة',
                'ordering': ['created_at'],
                'unique_together': {('patient', 'committee_session')},
            },
        ),
        migrations.AddField(
            model_name='committeesession',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee.doctor'),
        ),
        migrations.CreateModel(
            name='CommitteeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_text', models.TextField(verbose_name='نص التوصية النهائي')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية للقرار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوصية')),
                ('committee_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='committee.committeecase', verbose_name='الحالة الطبية المعروضة')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='committee.procedure', verbose_name='الإجراء الطبي الموصى به')),
            ],
            options={
                'verbose_name': 'توصية اللجنة',
                'verbose_name_plural': 'توصيات وقرارات اللجان',
                'ordering': ['-created_at'],
            },
        ),
    ]
