# Generated by Django 5.2.14 on 2026-05-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='category',
            field=models.CharField(choices=[('diagnostic', 'فحوصات'), ('therapeutic', 'اجراء علاجي')], default='اجراء علاجي', max_length=50, verbose_name='تصنيف الإجراء الطبي'),
        ),
    ]
