# Generated by Django 5.2.14 on 2026-07-15 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_alter_procedure_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeerecommendation',
            name='no_of_sessions',
            field=models.PositiveSmallIntegerField(blank=True, max_length=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
