# Generated by Django 5.2.14 on 2026-07-15 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0003_committeerecommendation_no_of_sessions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['category', 'name', 'price'], 'verbose_name': 'إجراء طبي', 'verbose_name_plural': 'الإجراءات الطبية'},
        ),
        migrations.AddField(
            model_name='procedure',
            name='price',
            field=models.CharField(blank=True, choices=[('27000 سبعة وعشرون ألف ', '27000'), ('28000 ثمانية وعشرون ألف', '28000')], null=True, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='committeerecommendation',
            name='no_of_sessions',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='category',
            field=models.CharField(choices=[('diagnostic', 'فحوصات'), ('gamaknife', 'جاما نايف'), ('radiosurgery', 'جراحة إشعاعية')], default='جاما نايف', max_length=50, verbose_name='تصنيف الإجراء الطبي'),
        ),
    ]
