# Generated by Django 5.2.14 on 2026-07-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0004_alter_procedure_options_procedure_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committeesession',
            options={'ordering': ['-session_date', '-created_at'], 'verbose_name': 'جلسة لجنة', 'verbose_name_plural': 'جلسات اللجان'},
        ),
        migrations.AlterField(
            model_name='committeesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='committeesession',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee.doctor', verbose_name='الطبيب'),
        ),
        migrations.AlterField(
            model_name='committeesession',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشطة'),
        ),
        migrations.AlterField(
            model_name='committeesession',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='committeesession',
            name='session_date',
            field=models.DateField(verbose_name='تاريخ الجلسة'),
        ),
        migrations.AlterField(
            model_name='committeesession',
            name='status',
            field=models.CharField(choices=[('active', 'نشطة'), ('closed', 'مغلقة')], default='active', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddConstraint(
            model_name='committeesession',
            constraint=models.UniqueConstraint(fields=('session_date',), name='unique_committee_session_per_day'),
        ),
    ]
