# Generated by Django 5.2.14 on 2026-07-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0005_alter_committeesession_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeesession',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='committeesession',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'قيد التجهيز'), ('COMPLETED', 'مكتملة')], default='PREPARING', max_length=20, verbose_name='الحالة'),
        ),
    ]
