# Generated by Django 5.2.14 on 2026-05-20 08:51

import apps.patients.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'الرقم القومي يجب أن يتكون من 14 رقماً.')], verbose_name='الرقم القومي')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم بالكامل')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'رقم الهاتف غير صحيح.')], verbose_name='رقم الهاتف')),
                ('governorate', models.CharField(choices=[('CAI', 'القاهرة'), ('ALX', 'الإسكندرية'), ('GIZ', 'الجيزة'), ('QLY', 'القليوبية'), ('PSD', 'بورسعيد'), ('SUZ', 'السويس'), ('GHR', 'الغربية'), ('DKH', 'الدقهلية'), ('ASW', 'أسوان'), ('LUX', 'الأقصر')], max_length=3, verbose_name='المحافظة')),
                ('affiliated_branch', models.CharField(choices=[('HQ', 'الفرع الرئيسي'), ('NTH', 'فرع الوجه البحري'), ('STH', 'فرع الوجه القبلي')], max_length=3, verbose_name='الفرع التابع له')),
                ('diagnosis', models.TextField(verbose_name='التشخيص الطبي المبدئي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'المرضى',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['national_id'], name='patients_pa_nationa_70cc77_idx'), models.Index(fields=['full_name'], name='patients_pa_full_na_b75abe_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('NID', 'بطاقة الرقم القومي'), ('REP', 'تقرير طبي'), ('LAB', 'نتائج التحاليل'), ('RAD', 'الأشعة')], max_length=3, verbose_name='نوع المستند')),
                ('file', models.FileField(upload_to=apps.patients.models.patient_directory_path, verbose_name='الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'مستند المريض',
                'verbose_name_plural': 'مستندات المرضى',
                'ordering': ['-created_at'],
            },
        ),
    ]
