# Generated by Django 5.2.14 on 2026-05-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='affiliated_branch',
            field=models.CharField(choices=[('AST', 'فرع اسيوط'), ('BHR', 'فرع البحيرة'), ('GIZ', 'فرع الجيزة'), ('DKH', 'فرع الدقهلية'), ('SHR', 'فرع الشرقية'), ('GHB', 'فرع الغربية'), ('FYM', 'فرع الفيوم'), ('CAI', 'فرع القاهرة'), ('QLY', 'فرع القليوبية'), ('MNF', 'فرع المنوفية'), ('MNY', 'فرع المنيا'), ('BNS', 'فرع بنى سويف'), ('DMT', 'فرع دمياط'), ('SHG', 'فرع سوهاج'), ('NSN', 'فرع شمال سيناء'), ('NWD', 'فرع شمال غرب الدلتا'), ('QNA', 'فرع قنا'), ('KSH', 'فرع كفر الشيخ'), ('RDS', 'منطقة البحر الاحمر'), ('NWV', 'منطقة الوادى الجديد'), ('MTR', 'منطقة مطروح')], max_length=3, verbose_name='الفرع التابع له'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='governorate',
            field=models.CharField(choices=[('AST', 'اسيوط'), ('BHR', 'البحيرة'), ('GIZ', 'الجيزة'), ('DKH', 'الدقهلية'), ('SHR', 'الشرقية'), ('GHB', 'الغربية'), ('FYM', 'الفيوم'), ('CAI', 'القاهرة'), ('QLY', 'القليوبية'), ('MNF', 'المنوفية'), ('MNY', 'المنيا'), ('BNS', 'بنى سويف'), ('DMT', 'دمياط'), ('SHG', 'سوهاج'), ('NSN', 'شمال سيناء'), ('NWD', 'شمال غرب الدلتا'), ('QNA', 'قنا'), ('KSH', 'كفر الشيخ'), ('RDS', 'البحر الاحمر'), ('NWV', 'الوادى الجديد'), ('MTR', 'مطروح')], max_length=3, verbose_name='المحافظة'),
        ),
    ]
