# Generated by Django 5.2.14 on 2026-06-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_affiliated_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance_law',
            field=models.CharField(choices=[('RET', 'معاش ق79'), ('STD', 'طلبة'), ('CID', 'مواليد ق99'), ('EMP', 'موظف ق79')], default='EMP', max_length=3, verbose_name='القانون'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_no',
            field=models.CharField(max_length=20, null=True, verbose_name='الرقم التأميني'),
        ),
    ]
