# Generated by Django 5.2.14 on 2026-06-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_insurance_law_patient_insurance_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم التأميني'),
        ),
    ]
