# Generated by Django 5.2.14 on 2026-06-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_insurance_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance_law',
            field=models.CharField(choices=[('RET', 'معاش ق79'), ('STD', 'طلبة'), ('CID', 'مواليد ق99'), ('EMP', 'موظف ق79')], max_length=3, verbose_name='القانون'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_no',
            field=models.CharField(max_length=20, verbose_name='الرقم التأميني'),
        ),
    ]
